data:
  noisy_files_path: /home/dev/other/data_vad/noise
  clean_files_path: /home/dev/other/data_vad/LibriSpeech_wav
  test_files_path: /home/dev/other/data_vad/for_devs
  sr: 16000
  processing:
    snr_range: [5, 35]
    reverb_proportion: 0.5
    silence_length: 0.2
    target_dB_FS: -25
    target_dB_FS_floating_value: 10
    vad_mode: 1
    data_bit: 16
    noise_proportion: 0.75

training:
  batch_size: 32
  save_checkpoint_interval: 1
  validation_interval: 2
  save_max_metric_score: true
  lr: 1e-4
  weight_decay: 1e-3
  epochs: 100
  clip_grad_norm_value: 5
  loss:
    reduction: "none"
    silent_weight: 4

acoustic:
  n_fft: 320
  win_length: 320
  hop_length: 160
  center: true
  n_mel: 80

model:
  rnn_layers: 2
  rnn_units: 128
  kernel_num: [1, 32, 64, 128, 256]
  fc_hidden_dim: 128
  fft_len: 320
  look_ahead: 2
  use_offline_norm: true
  spec_size: 80

env:
  gpu: 1
  save_dir: "./experiments"
  seed: 7
  workers: 6

metrics: ["ROC_AUC", "EER", "FNR_1_FPR", "FPR_1_FNR"]
